echo off
call compile-shared.bat
call compile-login.bat
call compile-main.bat
call compile-services.bat
call compile-contact.bat
call compile-team.bat
call compile-wip.bat
call compile-methodology.bat
call compile-partners.bat 
call compile-publications.bat 
call compile-resources.bat 
call compile-vision.bat 
