echo off
call compileSharedStyles.bat
call compileLoginStyles.bat
call compileMainStyles.bat
call compileServicesStyles.bat
call compileContactStyles.bat
call compileAboutStyles.bat
call compileNewsStyles.bat
call compileTeamStyles.bat
call compilePhilosophyStyles.bat
call compileAuthenticatorStyles.bat
call compileWipStyles.bat